apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  MINIO_ACCESS_KEY_ID: user
  MINIO_SECRET_ACCESS_KEY: password
  MINIO_STORAGE_BUCKET_NAME: static
  MINIO_API: "http://172.17.0.1:9000"
