# Default values for web-app-minio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


namespace: default

# Deployment
replicas: 1
image:
  repository: garovu/django-minio
  tag: latest
limits:
  memory: "1024Mi"
  cpu: "1000m"
containerPort: 8000


# ConfigMap
configMap:
  MINIO_ACCESS_KEY_ID: user
  MINIO_SECRET_ACCESS_KEY: password
  MINIO_STORAGE_BUCKET_NAME: static
  # MINIO_API: "http://172.17.0.1:9000"

# Service
service:
  type: ClusterIP
  port: 8000
  protocol: TCP


# Minio Setup
minio:
  namespace: default