apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: first-daemonset
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      name: monitoring
  template:
    metadata:
      labels:
        name: monitoring
    spec:
      containers:
        - name: busybox-container
          image: busybox
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
