apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: web-app-daemonset
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      name: web-app
  template:
    metadata:
      labels:
        name: web-app
    spec:
      containers:
      - name: hello-ctr
        image: busybox
        volumeMounts:
        - name: varlog
          mountPath: /var/log
      volumes:
      - name: varlog
        hostPath:
          path: /var/log