apiVersion: v1
kind: Service
metadata:
  name: first-nodeport
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector:
    zone: dev


---

apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30001
      targetPort: 9090
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: gix