apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: default
  labels:
    app: busybox
    version: v1
    zone: dev
spec:
  containers:
    - name: busybox-container
      image: busybox
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: fruits
          mountPath: /mnt
          readOnly: true
      envFrom:
        - secretRef:
            name: api-key
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
  volumes:
    - name: fruits
      configMap:
        name: first-configmap
        items:
          - key: fruits.json
            path: data.json
