apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  namespace: default
  labels:
    app: busybox
    version: v1
    zone: dev
spec:
  containers:
  - name: tool-kit 
    image: busybox
    command: 
      - sleep
      - "3600"
    volumeMounts:
      - name: fruits
        mountPath: /mnt
        readOnly: true
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "128Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
  volumes:
    - name: fruits
      configMap:
        name: first-cm
        items:
          - key: fruits.json
            path: data.json
        