apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: first-statefulset
spec:
  selector:
    matchLabels:
      app: statefull-app
  serviceName: headless-service
  replicas: 3
  template:
    metadata:
      labels:
        app: statefull-app
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - name: http-port
              containerPort: 80
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None
  selector:
    app: statefull-app
  ports:
    - port: 80
      targetPort: http-port
