apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minio-dev
spec:
  resources:
    requests:
      storage: 1000Mi
  volumeMode: Filesystem
  storageClassName: ""
  volumeName: minio-pv # Specific PV to PVC connect
  accessModes:
    - ReadWriteOnce