apiVersion: v1
kind: Service
metadata:
  name: "{{ include "web-app-minio.name" . }}-svc"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "web-app-minio.selectorLabels" . | nindent 4}}
    
