apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-sc
spec:
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  storageClassName: nfs-storage-class
  accessModes:
    - ReadWriteMany
