apiVersion: v1
kind: Pod
metadata:
  name: pod-sc
  labels:
    version: v1
    zone: dev
spec:
  containers:
    - name: sh
      image: busybox:1.36
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: nfs-pvc
          mountPath: /usr/share
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "512Mi"
          cpu: "1000m"
        limits:
          memory: "1024Mi"
          cpu: "2000m"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: nfs-pvc-sc
