---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "minio.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  containers:
    - name: {{ .Chart.Name }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      pullPolicy: {{ .Values.image.pullPolicy }}
      resources:
        limits:
          memory: {{ .Values.limits.memory }}
          cpu: {{ .Values.limits.cpu }}
      envFrom:
        - configMapRef:
            name: "{{ include "minio.name" . }}-cm"

      {{- with .Values.command }}
      command:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}

      {{- with .Values.args }}
      args:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
      {{- with .Values.volumeMounts }}
      volumeMounts:
        {{- toYaml . | nindent 8 -}}
      {{- end -}}
    {{- with .Values.volumes }}
  volumes:
    {{- toYaml . | nindent 6 -}}
  {{- end -}}