apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: cluster
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 -}}
