apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "minio.name" . }}-pvc"
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistenceClaim.storage }}
  volumeMode: {{ .Values.persistenceClaim.volumeMode }}
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: "{{ include "minio.name" . }}-pv"

